#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 125
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 66
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_LF = 1,
  sym_comment = 2,
  anon_sym_SEMI = 3,
  anon_sym_let = 4,
  anon_sym_EQ = 5,
  anon_sym_LPAREN = 6,
  anon_sym_COMMA = 7,
  anon_sym_RPAREN = 8,
  anon_sym_EQ_GT = 9,
  anon_sym_LBRACK = 10,
  anon_sym_RBRACK = 11,
  anon_sym_capture = 12,
  anon_sym_cmd = 13,
  anon_sym_LBRACE = 14,
  anon_sym_RBRACE = 15,
  anon_sym_in = 16,
  anon_sym_PIPE_PIPE = 17,
  anon_sym_AMP_AMP = 18,
  anon_sym_PIPE = 19,
  anon_sym_GT = 20,
  anon_sym_LT = 21,
  anon_sym_GT_GT = 22,
  sym_istr = 23,
  sym_int = 24,
  sym_str = 25,
  sym_identifier = 26,
  sym_word = 27,
  sym_source_file = 28,
  sym__statement_line = 29,
  sym__statement = 30,
  sym_let_statement = 31,
  sym_var_def = 32,
  sym__strong_expr = 33,
  sym_identifier_value = 34,
  sym_call = 35,
  sym_args = 36,
  sym__callee = 37,
  sym__expr = 38,
  sym__value = 39,
  sym_capture = 40,
  sym__cmd_blk = 41,
  sym__cmd_in_blk = 42,
  sym_cmd_vars = 43,
  sym_cmd_var_stmt = 44,
  sym__cmd_stmt = 45,
  sym_cmd_ctx = 46,
  sym__cmd_list = 47,
  sym_cmd_op = 48,
  sym_cmd_chain = 49,
  sym__cmd_chain_part = 50,
  sym_pipeline = 51,
  sym_cmd = 52,
  sym_cmd_name = 53,
  sym_redir_kind = 54,
  sym_redir = 55,
  sym__word = 56,
  aux_sym_source_file_repeat1 = 57,
  aux_sym_source_file_repeat2 = 58,
  aux_sym_args_repeat1 = 59,
  aux_sym__cmd_in_blk_repeat1 = 60,
  aux_sym_cmd_vars_repeat1 = 61,
  aux_sym__cmd_list_repeat1 = 62,
  aux_sym_pipeline_repeat1 = 63,
  aux_sym_cmd_repeat1 = 64,
  aux_sym_cmd_repeat2 = 65,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [sym_comment] = "comment",
  [anon_sym_SEMI] = ";",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_capture] = "capture",
  [anon_sym_cmd] = "cmd",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_in] = "in",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_PIPE] = "|",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_GT_GT] = ">>",
  [sym_istr] = "istr",
  [sym_int] = "int",
  [sym_str] = "str",
  [sym_identifier] = "identifier",
  [sym_word] = "word",
  [sym_source_file] = "source_file",
  [sym__statement_line] = "_statement_line",
  [sym__statement] = "_statement",
  [sym_let_statement] = "let_statement",
  [sym_var_def] = "var_def",
  [sym__strong_expr] = "_strong_expr",
  [sym_identifier_value] = "identifier_value",
  [sym_call] = "call",
  [sym_args] = "args",
  [sym__callee] = "_callee",
  [sym__expr] = "_expr",
  [sym__value] = "_value",
  [sym_capture] = "capture",
  [sym__cmd_blk] = "_cmd_blk",
  [sym__cmd_in_blk] = "_cmd_in_blk",
  [sym_cmd_vars] = "cmd_vars",
  [sym_cmd_var_stmt] = "cmd_var_stmt",
  [sym__cmd_stmt] = "_cmd_stmt",
  [sym_cmd_ctx] = "cmd_ctx",
  [sym__cmd_list] = "_cmd_list",
  [sym_cmd_op] = "cmd_op",
  [sym_cmd_chain] = "cmd_chain",
  [sym__cmd_chain_part] = "_cmd_chain_part",
  [sym_pipeline] = "pipeline",
  [sym_cmd] = "cmd",
  [sym_cmd_name] = "cmd_name",
  [sym_redir_kind] = "redir_kind",
  [sym_redir] = "redir",
  [sym__word] = "_word",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_args_repeat1] = "args_repeat1",
  [aux_sym__cmd_in_blk_repeat1] = "_cmd_in_blk_repeat1",
  [aux_sym_cmd_vars_repeat1] = "cmd_vars_repeat1",
  [aux_sym__cmd_list_repeat1] = "_cmd_list_repeat1",
  [aux_sym_pipeline_repeat1] = "pipeline_repeat1",
  [aux_sym_cmd_repeat1] = "cmd_repeat1",
  [aux_sym_cmd_repeat2] = "cmd_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [sym_comment] = sym_comment,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_capture] = anon_sym_capture,
  [anon_sym_cmd] = anon_sym_cmd,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [sym_istr] = sym_istr,
  [sym_int] = sym_int,
  [sym_str] = sym_str,
  [sym_identifier] = sym_identifier,
  [sym_word] = sym_word,
  [sym_source_file] = sym_source_file,
  [sym__statement_line] = sym__statement_line,
  [sym__statement] = sym__statement,
  [sym_let_statement] = sym_let_statement,
  [sym_var_def] = sym_var_def,
  [sym__strong_expr] = sym__strong_expr,
  [sym_identifier_value] = sym_identifier_value,
  [sym_call] = sym_call,
  [sym_args] = sym_args,
  [sym__callee] = sym__callee,
  [sym__expr] = sym__expr,
  [sym__value] = sym__value,
  [sym_capture] = sym_capture,
  [sym__cmd_blk] = sym__cmd_blk,
  [sym__cmd_in_blk] = sym__cmd_in_blk,
  [sym_cmd_vars] = sym_cmd_vars,
  [sym_cmd_var_stmt] = sym_cmd_var_stmt,
  [sym__cmd_stmt] = sym__cmd_stmt,
  [sym_cmd_ctx] = sym_cmd_ctx,
  [sym__cmd_list] = sym__cmd_list,
  [sym_cmd_op] = sym_cmd_op,
  [sym_cmd_chain] = sym_cmd_chain,
  [sym__cmd_chain_part] = sym__cmd_chain_part,
  [sym_pipeline] = sym_pipeline,
  [sym_cmd] = sym_cmd,
  [sym_cmd_name] = sym_cmd_name,
  [sym_redir_kind] = sym_redir_kind,
  [sym_redir] = sym_redir,
  [sym__word] = sym__word,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_args_repeat1] = aux_sym_args_repeat1,
  [aux_sym__cmd_in_blk_repeat1] = aux_sym__cmd_in_blk_repeat1,
  [aux_sym_cmd_vars_repeat1] = aux_sym_cmd_vars_repeat1,
  [aux_sym__cmd_list_repeat1] = aux_sym__cmd_list_repeat1,
  [aux_sym_pipeline_repeat1] = aux_sym_pipeline_repeat1,
  [aux_sym_cmd_repeat1] = aux_sym_cmd_repeat1,
  [aux_sym_cmd_repeat2] = aux_sym_cmd_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_capture] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cmd] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_istr] = {
    .visible = true,
    .named = true,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [sym_str] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement_line] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_let_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_var_def] = {
    .visible = true,
    .named = true,
  },
  [sym__strong_expr] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier_value] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_args] = {
    .visible = true,
    .named = true,
  },
  [sym__callee] = {
    .visible = false,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_capture] = {
    .visible = true,
    .named = true,
  },
  [sym__cmd_blk] = {
    .visible = false,
    .named = true,
  },
  [sym__cmd_in_blk] = {
    .visible = false,
    .named = true,
  },
  [sym_cmd_vars] = {
    .visible = true,
    .named = true,
  },
  [sym_cmd_var_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym__cmd_stmt] = {
    .visible = false,
    .named = true,
  },
  [sym_cmd_ctx] = {
    .visible = true,
    .named = true,
  },
  [sym__cmd_list] = {
    .visible = false,
    .named = true,
  },
  [sym_cmd_op] = {
    .visible = true,
    .named = true,
  },
  [sym_cmd_chain] = {
    .visible = true,
    .named = true,
  },
  [sym__cmd_chain_part] = {
    .visible = false,
    .named = true,
  },
  [sym_pipeline] = {
    .visible = true,
    .named = true,
  },
  [sym_cmd] = {
    .visible = true,
    .named = true,
  },
  [sym_cmd_name] = {
    .visible = true,
    .named = true,
  },
  [sym_redir_kind] = {
    .visible = true,
    .named = true,
  },
  [sym_redir] = {
    .visible = true,
    .named = true,
  },
  [sym__word] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_args_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__cmd_in_blk_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_cmd_vars_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__cmd_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pipeline_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_cmd_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_cmd_repeat2] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0)
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '#') ADVANCE(1);
      if (lookahead == '&') ADVANCE(4);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == '(') ADVANCE(23);
      if (lookahead == ')') ADVANCE(25);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == ';') ADVANCE(18);
      if (lookahead == '<') ADVANCE(39);
      if (lookahead == '=') ADVANCE(22);
      if (lookahead == '>') ADVANCE(38);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == ']') ADVANCE(28);
      if (lookahead == 'c') ADVANCE(47);
      if (lookahead == 'i') ADVANCE(52);
      if (lookahead == 'l') ADVANCE(49);
      if (lookahead == '{') ADVANCE(31);
      if (lookahead == '|') ADVANCE(37);
      if (lookahead == '}') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(44);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 4:
      if (lookahead == '&') ADVANCE(36);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(45);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '\'') ADVANCE(46);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(33);
      END_STATE();
    case 8:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(8)
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == '(') ADVANCE(23);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == 'l') ADVANCE(51);
      if (lookahead == '}') ADVANCE(32);
      if (lookahead == '$' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '/') ||
          lookahead == ':') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 9:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(9)
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '&') ADVANCE(4);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == '(') ADVANCE(23);
      if (lookahead == ')') ADVANCE(25);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == ';') ADVANCE(18);
      if (lookahead == '<') ADVANCE(39);
      if (lookahead == '>') ADVANCE(38);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == ']') ADVANCE(28);
      if (lookahead == '|') ADVANCE(37);
      if (lookahead == '}') ADVANCE(32);
      if (lookahead == '$' ||
          ('+' <= lookahead && lookahead <= '/') ||
          lookahead == ':') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 10:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(10)
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == '(') ADVANCE(23);
      if (lookahead == ')') ADVANCE(25);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == ']') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(44);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 11:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(11)
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '(') ADVANCE(23);
      if (lookahead == ')') ADVANCE(25);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == ';') ADVANCE(18);
      if (lookahead == ']') ADVANCE(28);
      if (lookahead == 'i') ADVANCE(7);
      if (lookahead == '}') ADVANCE(32);
      END_STATE();
    case 12:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(12)
      if (lookahead == 'i') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 13:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(13)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(14)
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '#') ADVANCE(1);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == '(') ADVANCE(23);
      if (lookahead == '=') ADVANCE(21);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == 'c') ADVANCE(47);
      if (lookahead == 'l') ADVANCE(49);
      if (lookahead == '{') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(44);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_let);
      if (lookahead == '$' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '/') ||
          lookahead == ':') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '>') ADVANCE(26);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_capture);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_cmd);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_in);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '|') ADVANCE(35);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '>') ADVANCE(40);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_istr);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_istr);
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_int);
      if (lookahead == '$' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '/') ||
          lookahead == ':') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_int);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(44);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_str);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_str);
      if (lookahead == '\'') ADVANCE(45);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(53);
      if (lookahead == 'm') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(57);
      if (lookahead == '$' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '/') ||
          lookahead == ':') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(19);
      if (lookahead == '$' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '/') ||
          lookahead == ':') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '$' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '/') ||
          lookahead == ':') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '$' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 14},
  [2] = {.lex_state = 8},
  [3] = {.lex_state = 8},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 14},
  [11] = {.lex_state = 9},
  [12] = {.lex_state = 9},
  [13] = {.lex_state = 14},
  [14] = {.lex_state = 14},
  [15] = {.lex_state = 14},
  [16] = {.lex_state = 9},
  [17] = {.lex_state = 9},
  [18] = {.lex_state = 9},
  [19] = {.lex_state = 9},
  [20] = {.lex_state = 9},
  [21] = {.lex_state = 9},
  [22] = {.lex_state = 9},
  [23] = {.lex_state = 9},
  [24] = {.lex_state = 9},
  [25] = {.lex_state = 9},
  [26] = {.lex_state = 14},
  [27] = {.lex_state = 10},
  [28] = {.lex_state = 10},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 10},
  [31] = {.lex_state = 10},
  [32] = {.lex_state = 10},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 14},
  [36] = {.lex_state = 10},
  [37] = {.lex_state = 14},
  [38] = {.lex_state = 10},
  [39] = {.lex_state = 14},
  [40] = {.lex_state = 14},
  [41] = {.lex_state = 9},
  [42] = {.lex_state = 14},
  [43] = {.lex_state = 9},
  [44] = {.lex_state = 14},
  [45] = {.lex_state = 14},
  [46] = {.lex_state = 14},
  [47] = {.lex_state = 10},
  [48] = {.lex_state = 10},
  [49] = {.lex_state = 10},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 8},
  [52] = {.lex_state = 9},
  [53] = {.lex_state = 8},
  [54] = {.lex_state = 8},
  [55] = {.lex_state = 10},
  [56] = {.lex_state = 8},
  [57] = {.lex_state = 11},
  [58] = {.lex_state = 11},
  [59] = {.lex_state = 11},
  [60] = {.lex_state = 11},
  [61] = {.lex_state = 9},
  [62] = {.lex_state = 9},
  [63] = {.lex_state = 9},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 9},
  [67] = {.lex_state = 9},
  [68] = {.lex_state = 11},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 9},
  [71] = {.lex_state = 9},
  [72] = {.lex_state = 11},
  [73] = {.lex_state = 11},
  [74] = {.lex_state = 11},
  [75] = {.lex_state = 11},
  [76] = {.lex_state = 11},
  [77] = {.lex_state = 11},
  [78] = {.lex_state = 12},
  [79] = {.lex_state = 12},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 12},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 12},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 13},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 14},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 13},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 14},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_capture] = ACTIONS(1),
    [anon_sym_cmd] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [sym_istr] = ACTIONS(1),
    [sym_int] = ACTIONS(1),
    [sym_str] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(117),
    [sym__statement_line] = STATE(15),
    [sym__statement] = STATE(35),
    [sym_let_statement] = STATE(35),
    [sym__strong_expr] = STATE(116),
    [sym_identifier_value] = STATE(116),
    [sym_call] = STATE(116),
    [sym__callee] = STATE(102),
    [sym__value] = STATE(116),
    [sym_capture] = STATE(112),
    [sym__cmd_blk] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(10),
    [aux_sym_source_file_repeat2] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_capture] = ACTIONS(15),
    [anon_sym_cmd] = ACTIONS(17),
    [sym_istr] = ACTIONS(19),
    [sym_int] = ACTIONS(21),
    [sym_str] = ACTIONS(19),
    [sym_identifier] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 20,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LF,
    ACTIONS(27), 1,
      anon_sym_let,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(8), 1,
      aux_sym__cmd_in_blk_repeat1,
    STATE(11), 1,
      sym_cmd_name,
    STATE(19), 1,
      sym_cmd_vars,
    STATE(21), 1,
      aux_sym__cmd_list_repeat1,
    STATE(41), 1,
      aux_sym_pipeline_repeat1,
    STATE(65), 1,
      sym_cmd,
    STATE(69), 1,
      sym_pipeline,
    STATE(87), 1,
      sym__cmd_chain_part,
    STATE(88), 1,
      sym_cmd_chain,
    STATE(91), 1,
      sym__cmd_list,
    STATE(104), 1,
      sym__cmd_in_blk,
    ACTIONS(31), 2,
      sym_istr,
      sym_str,
    ACTIONS(33), 3,
      sym_int,
      sym_identifier,
      sym_word,
    STATE(23), 3,
      sym__expr,
      sym__value,
      sym__word,
    STATE(92), 3,
      sym_cmd_var_stmt,
      sym__cmd_stmt,
      sym_cmd_ctx,
  [68] = 20,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_let,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_LF,
    STATE(8), 1,
      aux_sym__cmd_in_blk_repeat1,
    STATE(11), 1,
      sym_cmd_name,
    STATE(19), 1,
      sym_cmd_vars,
    STATE(21), 1,
      aux_sym__cmd_list_repeat1,
    STATE(41), 1,
      aux_sym_pipeline_repeat1,
    STATE(51), 1,
      aux_sym_source_file_repeat1,
    STATE(65), 1,
      sym_cmd,
    STATE(69), 1,
      sym_pipeline,
    STATE(87), 1,
      sym__cmd_chain_part,
    STATE(88), 1,
      sym_cmd_chain,
    STATE(91), 1,
      sym__cmd_list,
    STATE(119), 1,
      sym__cmd_in_blk,
    ACTIONS(31), 2,
      sym_istr,
      sym_str,
    ACTIONS(33), 3,
      sym_int,
      sym_identifier,
      sym_word,
    STATE(23), 3,
      sym__expr,
      sym__value,
      sym__word,
    STATE(92), 3,
      sym_cmd_var_stmt,
      sym__cmd_stmt,
      sym_cmd_ctx,
  [136] = 20,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_let,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_LF,
    STATE(8), 1,
      aux_sym__cmd_in_blk_repeat1,
    STATE(11), 1,
      sym_cmd_name,
    STATE(19), 1,
      sym_cmd_vars,
    STATE(21), 1,
      aux_sym__cmd_list_repeat1,
    STATE(41), 1,
      aux_sym_pipeline_repeat1,
    STATE(51), 1,
      aux_sym_source_file_repeat1,
    STATE(65), 1,
      sym_cmd,
    STATE(69), 1,
      sym_pipeline,
    STATE(87), 1,
      sym__cmd_chain_part,
    STATE(88), 1,
      sym_cmd_chain,
    STATE(91), 1,
      sym__cmd_list,
    STATE(107), 1,
      sym__cmd_in_blk,
    ACTIONS(31), 2,
      sym_istr,
      sym_str,
    ACTIONS(33), 3,
      sym_int,
      sym_identifier,
      sym_word,
    STATE(23), 3,
      sym__expr,
      sym__value,
      sym__word,
    STATE(92), 3,
      sym_cmd_var_stmt,
      sym__cmd_stmt,
      sym_cmd_ctx,
  [204] = 20,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_let,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_LF,
    STATE(7), 1,
      aux_sym_source_file_repeat1,
    STATE(8), 1,
      aux_sym__cmd_in_blk_repeat1,
    STATE(11), 1,
      sym_cmd_name,
    STATE(19), 1,
      sym_cmd_vars,
    STATE(21), 1,
      aux_sym__cmd_list_repeat1,
    STATE(41), 1,
      aux_sym_pipeline_repeat1,
    STATE(65), 1,
      sym_cmd,
    STATE(69), 1,
      sym_pipeline,
    STATE(87), 1,
      sym__cmd_chain_part,
    STATE(88), 1,
      sym_cmd_chain,
    STATE(91), 1,
      sym__cmd_list,
    STATE(107), 1,
      sym__cmd_in_blk,
    ACTIONS(31), 2,
      sym_istr,
      sym_str,
    ACTIONS(33), 3,
      sym_int,
      sym_identifier,
      sym_word,
    STATE(23), 3,
      sym__expr,
      sym__value,
      sym__word,
    STATE(92), 3,
      sym_cmd_var_stmt,
      sym__cmd_stmt,
      sym_cmd_ctx,
  [272] = 20,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_let,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      anon_sym_LF,
    STATE(4), 1,
      aux_sym_source_file_repeat1,
    STATE(8), 1,
      aux_sym__cmd_in_blk_repeat1,
    STATE(11), 1,
      sym_cmd_name,
    STATE(19), 1,
      sym_cmd_vars,
    STATE(21), 1,
      aux_sym__cmd_list_repeat1,
    STATE(41), 1,
      aux_sym_pipeline_repeat1,
    STATE(65), 1,
      sym_cmd,
    STATE(69), 1,
      sym_pipeline,
    STATE(87), 1,
      sym__cmd_chain_part,
    STATE(88), 1,
      sym_cmd_chain,
    STATE(91), 1,
      sym__cmd_list,
    STATE(119), 1,
      sym__cmd_in_blk,
    ACTIONS(31), 2,
      sym_istr,
      sym_str,
    ACTIONS(33), 3,
      sym_int,
      sym_identifier,
      sym_word,
    STATE(23), 3,
      sym__expr,
      sym__value,
      sym__word,
    STATE(92), 3,
      sym_cmd_var_stmt,
      sym__cmd_stmt,
      sym_cmd_ctx,
  [340] = 20,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_let,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_LF,
    STATE(8), 1,
      aux_sym__cmd_in_blk_repeat1,
    STATE(11), 1,
      sym_cmd_name,
    STATE(19), 1,
      sym_cmd_vars,
    STATE(21), 1,
      aux_sym__cmd_list_repeat1,
    STATE(41), 1,
      aux_sym_pipeline_repeat1,
    STATE(51), 1,
      aux_sym_source_file_repeat1,
    STATE(65), 1,
      sym_cmd,
    STATE(69), 1,
      sym_pipeline,
    STATE(87), 1,
      sym__cmd_chain_part,
    STATE(88), 1,
      sym_cmd_chain,
    STATE(91), 1,
      sym__cmd_list,
    STATE(113), 1,
      sym__cmd_in_blk,
    ACTIONS(31), 2,
      sym_istr,
      sym_str,
    ACTIONS(33), 3,
      sym_int,
      sym_identifier,
      sym_word,
    STATE(23), 3,
      sym__expr,
      sym__value,
      sym__word,
    STATE(92), 3,
      sym_cmd_var_stmt,
      sym__cmd_stmt,
      sym_cmd_ctx,
  [408] = 17,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_let,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    STATE(9), 1,
      aux_sym__cmd_in_blk_repeat1,
    STATE(11), 1,
      sym_cmd_name,
    STATE(19), 1,
      sym_cmd_vars,
    STATE(21), 1,
      aux_sym__cmd_list_repeat1,
    STATE(41), 1,
      aux_sym_pipeline_repeat1,
    STATE(65), 1,
      sym_cmd,
    STATE(69), 1,
      sym_pipeline,
    STATE(87), 1,
      sym__cmd_chain_part,
    STATE(88), 1,
      sym_cmd_chain,
    STATE(91), 1,
      sym__cmd_list,
    ACTIONS(31), 2,
      sym_istr,
      sym_str,
    ACTIONS(33), 3,
      sym_int,
      sym_identifier,
      sym_word,
    STATE(23), 3,
      sym__expr,
      sym__value,
      sym__word,
    STATE(100), 3,
      sym_cmd_var_stmt,
      sym__cmd_stmt,
      sym_cmd_ctx,
  [467] = 17,
    ACTIONS(41), 1,
      anon_sym_let,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      anon_sym_LBRACK,
    STATE(9), 1,
      aux_sym__cmd_in_blk_repeat1,
    STATE(11), 1,
      sym_cmd_name,
    STATE(19), 1,
      sym_cmd_vars,
    STATE(21), 1,
      aux_sym__cmd_list_repeat1,
    STATE(41), 1,
      aux_sym_pipeline_repeat1,
    STATE(65), 1,
      sym_cmd,
    STATE(69), 1,
      sym_pipeline,
    STATE(87), 1,
      sym__cmd_chain_part,
    STATE(88), 1,
      sym_cmd_chain,
    STATE(91), 1,
      sym__cmd_list,
    ACTIONS(50), 2,
      sym_istr,
      sym_str,
    ACTIONS(53), 3,
      sym_int,
      sym_identifier,
      sym_word,
    STATE(23), 3,
      sym__expr,
      sym__value,
      sym__word,
    STATE(114), 3,
      sym_cmd_var_stmt,
      sym__cmd_stmt,
      sym_cmd_ctx,
  [526] = 17,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_capture,
    ACTIONS(17), 1,
      anon_sym_cmd,
    ACTIONS(21), 1,
      sym_int,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    ACTIONS(58), 1,
      anon_sym_LF,
    STATE(26), 1,
      aux_sym_source_file_repeat1,
    STATE(102), 1,
      sym__callee,
    STATE(112), 1,
      sym_capture,
    ACTIONS(19), 2,
      sym_istr,
      sym_str,
    STATE(14), 2,
      sym__statement_line,
      aux_sym_source_file_repeat2,
    STATE(35), 3,
      sym__statement,
      sym_let_statement,
      sym__cmd_blk,
    STATE(116), 4,
      sym__strong_expr,
      sym_identifier_value,
      sym_call,
      sym__value,
  [585] = 10,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(62), 1,
      anon_sym_PIPE,
    ACTIONS(64), 1,
      anon_sym_GT,
    STATE(52), 1,
      sym_redir_kind,
    ACTIONS(66), 2,
      anon_sym_LT,
      anon_sym_GT_GT,
    ACTIONS(68), 2,
      sym_istr,
      sym_str,
    STATE(29), 2,
      sym_redir,
      aux_sym_cmd_repeat2,
    ACTIONS(70), 3,
      sym_int,
      sym_identifier,
      sym_word,
    STATE(12), 4,
      sym__expr,
      sym__value,
      sym__word,
      aux_sym_cmd_repeat1,
    ACTIONS(60), 6,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [629] = 10,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(64), 1,
      anon_sym_GT,
    ACTIONS(74), 1,
      anon_sym_PIPE,
    STATE(52), 1,
      sym_redir_kind,
    ACTIONS(66), 2,
      anon_sym_LT,
      anon_sym_GT_GT,
    ACTIONS(76), 2,
      sym_istr,
      sym_str,
    STATE(34), 2,
      sym_redir,
      aux_sym_cmd_repeat2,
    ACTIONS(78), 3,
      sym_int,
      sym_identifier,
      sym_word,
    STATE(16), 4,
      sym__expr,
      sym__value,
      sym__word,
      aux_sym_cmd_repeat1,
    ACTIONS(72), 6,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [673] = 15,
    ACTIONS(80), 1,
      ts_builtin_sym_end,
    ACTIONS(82), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_let,
    ACTIONS(88), 1,
      anon_sym_LPAREN,
    ACTIONS(91), 1,
      anon_sym_LBRACK,
    ACTIONS(94), 1,
      anon_sym_capture,
    ACTIONS(97), 1,
      anon_sym_cmd,
    ACTIONS(103), 1,
      sym_int,
    ACTIONS(106), 1,
      sym_identifier,
    STATE(102), 1,
      sym__callee,
    STATE(112), 1,
      sym_capture,
    ACTIONS(100), 2,
      sym_istr,
      sym_str,
    STATE(13), 2,
      sym__statement_line,
      aux_sym_source_file_repeat2,
    STATE(35), 3,
      sym__statement,
      sym_let_statement,
      sym__cmd_blk,
    STATE(116), 4,
      sym__strong_expr,
      sym_identifier_value,
      sym_call,
      sym__value,
  [726] = 15,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_capture,
    ACTIONS(17), 1,
      anon_sym_cmd,
    ACTIONS(21), 1,
      sym_int,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(109), 1,
      ts_builtin_sym_end,
    STATE(102), 1,
      sym__callee,
    STATE(112), 1,
      sym_capture,
    ACTIONS(19), 2,
      sym_istr,
      sym_str,
    STATE(13), 2,
      sym__statement_line,
      aux_sym_source_file_repeat2,
    STATE(35), 3,
      sym__statement,
      sym_let_statement,
      sym__cmd_blk,
    STATE(116), 4,
      sym__strong_expr,
      sym_identifier_value,
      sym_call,
      sym__value,
  [779] = 15,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_capture,
    ACTIONS(17), 1,
      anon_sym_cmd,
    ACTIONS(21), 1,
      sym_int,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    STATE(102), 1,
      sym__callee,
    STATE(112), 1,
      sym_capture,
    ACTIONS(19), 2,
      sym_istr,
      sym_str,
    STATE(13), 2,
      sym__statement_line,
      aux_sym_source_file_repeat2,
    STATE(35), 3,
      sym__statement,
      sym_let_statement,
      sym__cmd_blk,
    STATE(116), 4,
      sym__strong_expr,
      sym_identifier_value,
      sym_call,
      sym__value,
  [832] = 6,
    ACTIONS(113), 1,
      anon_sym_LBRACK,
    ACTIONS(116), 2,
      anon_sym_PIPE,
      anon_sym_GT,
    ACTIONS(118), 2,
      sym_istr,
      sym_str,
    ACTIONS(121), 3,
      sym_int,
      sym_identifier,
      sym_word,
    STATE(16), 4,
      sym__expr,
      sym__value,
      sym__word,
      aux_sym_cmd_repeat1,
    ACTIONS(111), 8,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT,
      anon_sym_GT_GT,
  [865] = 2,
    ACTIONS(126), 5,
      anon_sym_PIPE,
      anon_sym_GT,
      sym_int,
      sym_identifier,
      sym_word,
    ACTIONS(124), 13,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT,
      anon_sym_GT_GT,
      sym_istr,
      sym_str,
  [888] = 2,
    ACTIONS(130), 5,
      anon_sym_PIPE,
      anon_sym_GT,
      sym_int,
      sym_identifier,
      sym_word,
    ACTIONS(128), 13,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT,
      anon_sym_GT_GT,
      sym_istr,
      sym_str,
  [911] = 13,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    STATE(11), 1,
      sym_cmd_name,
    STATE(21), 1,
      aux_sym__cmd_list_repeat1,
    STATE(41), 1,
      aux_sym_pipeline_repeat1,
    STATE(65), 1,
      sym_cmd,
    STATE(69), 1,
      sym_pipeline,
    STATE(87), 1,
      sym__cmd_chain_part,
    STATE(88), 1,
      sym_cmd_chain,
    STATE(99), 1,
      sym__cmd_list,
    ACTIONS(31), 2,
      sym_istr,
      sym_str,
    ACTIONS(33), 3,
      sym_int,
      sym_identifier,
      sym_word,
    STATE(23), 3,
      sym__expr,
      sym__value,
      sym__word,
  [956] = 2,
    ACTIONS(134), 5,
      anon_sym_PIPE,
      anon_sym_GT,
      sym_int,
      sym_identifier,
      sym_word,
    ACTIONS(132), 13,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT,
      anon_sym_GT_GT,
      sym_istr,
      sym_str,
  [979] = 12,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    STATE(11), 1,
      sym_cmd_name,
    STATE(22), 1,
      aux_sym__cmd_list_repeat1,
    STATE(41), 1,
      aux_sym_pipeline_repeat1,
    STATE(65), 1,
      sym_cmd,
    STATE(69), 1,
      sym_pipeline,
    STATE(86), 1,
      sym_cmd_chain,
    STATE(87), 1,
      sym__cmd_chain_part,
    ACTIONS(31), 2,
      sym_istr,
      sym_str,
    ACTIONS(33), 3,
      sym_int,
      sym_identifier,
      sym_word,
    STATE(23), 3,
      sym__expr,
      sym__value,
      sym__word,
  [1021] = 12,
    ACTIONS(136), 1,
      anon_sym_LPAREN,
    ACTIONS(139), 1,
      anon_sym_LBRACK,
    STATE(11), 1,
      sym_cmd_name,
    STATE(22), 1,
      aux_sym__cmd_list_repeat1,
    STATE(41), 1,
      aux_sym_pipeline_repeat1,
    STATE(65), 1,
      sym_cmd,
    STATE(69), 1,
      sym_pipeline,
    STATE(87), 1,
      sym__cmd_chain_part,
    STATE(105), 1,
      sym_cmd_chain,
    ACTIONS(142), 2,
      sym_istr,
      sym_str,
    ACTIONS(145), 3,
      sym_int,
      sym_identifier,
      sym_word,
    STATE(23), 3,
      sym__expr,
      sym__value,
      sym__word,
  [1063] = 2,
    ACTIONS(150), 5,
      anon_sym_PIPE,
      anon_sym_GT,
      sym_int,
      sym_identifier,
      sym_word,
    ACTIONS(148), 11,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT,
      anon_sym_GT_GT,
      sym_istr,
      sym_str,
  [1084] = 11,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    STATE(11), 1,
      sym_cmd_name,
    STATE(41), 1,
      aux_sym_pipeline_repeat1,
    STATE(65), 1,
      sym_cmd,
    STATE(69), 1,
      sym_pipeline,
    STATE(87), 1,
      sym__cmd_chain_part,
    STATE(103), 1,
      sym_cmd_chain,
    ACTIONS(31), 2,
      sym_istr,
      sym_str,
    ACTIONS(33), 3,
      sym_int,
      sym_identifier,
      sym_word,
    STATE(23), 3,
      sym__expr,
      sym__value,
      sym__word,
  [1123] = 11,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    STATE(11), 1,
      sym_cmd_name,
    STATE(41), 1,
      aux_sym_pipeline_repeat1,
    STATE(65), 1,
      sym_cmd,
    STATE(69), 1,
      sym_pipeline,
    STATE(80), 1,
      sym_cmd_chain,
    STATE(87), 1,
      sym__cmd_chain_part,
    ACTIONS(31), 2,
      sym_istr,
      sym_str,
    ACTIONS(33), 3,
      sym_int,
      sym_identifier,
      sym_word,
    STATE(23), 3,
      sym__expr,
      sym__value,
      sym__word,
  [1162] = 4,
    ACTIONS(154), 1,
      anon_sym_LF,
    STATE(26), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(157), 5,
      anon_sym_let,
      anon_sym_capture,
      anon_sym_cmd,
      sym_int,
      sym_identifier,
    ACTIONS(152), 7,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_istr,
      sym_str,
  [1185] = 9,
    ACTIONS(159), 1,
      anon_sym_LPAREN,
    ACTIONS(164), 1,
      anon_sym_LBRACK,
    ACTIONS(170), 1,
      sym_int,
    ACTIONS(173), 1,
      sym_identifier,
    STATE(27), 1,
      aux_sym_args_repeat1,
    STATE(102), 1,
      sym__callee,
    ACTIONS(162), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
    ACTIONS(167), 2,
      sym_istr,
      sym_str,
    STATE(118), 4,
      sym__strong_expr,
      sym_identifier_value,
      sym_call,
      sym__value,
  [1218] = 9,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(176), 1,
      anon_sym_RPAREN,
    ACTIONS(180), 1,
      sym_int,
    STATE(36), 1,
      aux_sym_args_repeat1,
    STATE(102), 1,
      sym__callee,
    ACTIONS(178), 2,
      sym_istr,
      sym_str,
    STATE(98), 4,
      sym__strong_expr,
      sym_identifier_value,
      sym_call,
      sym__value,
  [1250] = 6,
    ACTIONS(64), 1,
      anon_sym_GT,
    ACTIONS(74), 1,
      anon_sym_PIPE,
    STATE(52), 1,
      sym_redir_kind,
    ACTIONS(66), 2,
      anon_sym_LT,
      anon_sym_GT_GT,
    STATE(33), 2,
      sym_redir,
      aux_sym_cmd_repeat2,
    ACTIONS(72), 6,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [1276] = 9,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(182), 1,
      anon_sym_RBRACK,
    ACTIONS(186), 1,
      sym_int,
    STATE(27), 1,
      aux_sym_args_repeat1,
    STATE(102), 1,
      sym__callee,
    ACTIONS(184), 2,
      sym_istr,
      sym_str,
    STATE(89), 4,
      sym__strong_expr,
      sym_identifier_value,
      sym_call,
      sym__value,
  [1308] = 9,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(188), 1,
      anon_sym_RBRACK,
    ACTIONS(192), 1,
      sym_int,
    STATE(30), 1,
      aux_sym_args_repeat1,
    STATE(102), 1,
      sym__callee,
    ACTIONS(190), 2,
      sym_istr,
      sym_str,
    STATE(90), 4,
      sym__strong_expr,
      sym_identifier_value,
      sym_call,
      sym__value,
  [1340] = 9,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(194), 1,
      anon_sym_RBRACK,
    ACTIONS(198), 1,
      sym_int,
    STATE(38), 1,
      aux_sym_args_repeat1,
    STATE(102), 1,
      sym__callee,
    ACTIONS(196), 2,
      sym_istr,
      sym_str,
    STATE(97), 4,
      sym__strong_expr,
      sym_identifier_value,
      sym_call,
      sym__value,
  [1372] = 6,
    ACTIONS(202), 1,
      anon_sym_PIPE,
    ACTIONS(204), 1,
      anon_sym_GT,
    STATE(52), 1,
      sym_redir_kind,
    ACTIONS(207), 2,
      anon_sym_LT,
      anon_sym_GT_GT,
    STATE(33), 2,
      sym_redir,
      aux_sym_cmd_repeat2,
    ACTIONS(200), 6,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [1398] = 6,
    ACTIONS(64), 1,
      anon_sym_GT,
    ACTIONS(212), 1,
      anon_sym_PIPE,
    STATE(52), 1,
      sym_redir_kind,
    ACTIONS(66), 2,
      anon_sym_LT,
      anon_sym_GT_GT,
    STATE(33), 2,
      sym_redir,
      aux_sym_cmd_repeat2,
    ACTIONS(210), 6,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [1424] = 4,
    ACTIONS(216), 1,
      anon_sym_LF,
    STATE(37), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(218), 5,
      anon_sym_let,
      anon_sym_capture,
      anon_sym_cmd,
      sym_int,
      sym_identifier,
    ACTIONS(214), 6,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_istr,
      sym_str,
  [1446] = 9,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(220), 1,
      anon_sym_RPAREN,
    ACTIONS(224), 1,
      sym_int,
    STATE(27), 1,
      aux_sym_args_repeat1,
    STATE(102), 1,
      sym__callee,
    ACTIONS(222), 2,
      sym_istr,
      sym_str,
    STATE(93), 4,
      sym__strong_expr,
      sym_identifier_value,
      sym_call,
      sym__value,
  [1478] = 4,
    ACTIONS(58), 1,
      anon_sym_LF,
    STATE(26), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(228), 5,
      anon_sym_let,
      anon_sym_capture,
      anon_sym_cmd,
      sym_int,
      sym_identifier,
    ACTIONS(226), 6,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_istr,
      sym_str,
  [1500] = 9,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(230), 1,
      anon_sym_RBRACK,
    ACTIONS(234), 1,
      sym_int,
    STATE(27), 1,
      aux_sym_args_repeat1,
    STATE(102), 1,
      sym__callee,
    ACTIONS(232), 2,
      sym_istr,
      sym_str,
    STATE(94), 4,
      sym__strong_expr,
      sym_identifier_value,
      sym_call,
      sym__value,
  [1532] = 2,
    ACTIONS(238), 5,
      anon_sym_let,
      anon_sym_capture,
      anon_sym_cmd,
      sym_int,
      sym_identifier,
    ACTIONS(236), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_istr,
      sym_str,
  [1549] = 2,
    ACTIONS(242), 5,
      anon_sym_let,
      anon_sym_capture,
      anon_sym_cmd,
      sym_int,
      sym_identifier,
    ACTIONS(240), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_istr,
      sym_str,
  [1566] = 7,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    STATE(11), 1,
      sym_cmd_name,
    STATE(43), 1,
      aux_sym_pipeline_repeat1,
    STATE(64), 1,
      sym_cmd,
    ACTIONS(31), 2,
      sym_istr,
      sym_str,
    ACTIONS(33), 3,
      sym_int,
      sym_identifier,
      sym_word,
    STATE(23), 3,
      sym__expr,
      sym__value,
      sym__word,
  [1593] = 2,
    ACTIONS(246), 5,
      anon_sym_let,
      anon_sym_capture,
      anon_sym_cmd,
      sym_int,
      sym_identifier,
    ACTIONS(244), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_istr,
      sym_str,
  [1610] = 7,
    ACTIONS(248), 1,
      anon_sym_LBRACK,
    STATE(11), 1,
      sym_cmd_name,
    STATE(43), 1,
      aux_sym_pipeline_repeat1,
    STATE(106), 1,
      sym_cmd,
    ACTIONS(251), 2,
      sym_istr,
      sym_str,
    ACTIONS(254), 3,
      sym_int,
      sym_identifier,
      sym_word,
    STATE(23), 3,
      sym__expr,
      sym__value,
      sym__word,
  [1637] = 2,
    ACTIONS(259), 5,
      anon_sym_let,
      anon_sym_capture,
      anon_sym_cmd,
      sym_int,
      sym_identifier,
    ACTIONS(257), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_istr,
      sym_str,
  [1654] = 2,
    ACTIONS(263), 5,
      anon_sym_let,
      anon_sym_capture,
      anon_sym_cmd,
      sym_int,
      sym_identifier,
    ACTIONS(261), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_istr,
      sym_str,
  [1671] = 2,
    ACTIONS(267), 5,
      anon_sym_let,
      anon_sym_capture,
      anon_sym_cmd,
      sym_int,
      sym_identifier,
    ACTIONS(265), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_istr,
      sym_str,
  [1688] = 7,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(269), 1,
      anon_sym_LBRACK,
    ACTIONS(273), 1,
      sym_int,
    STATE(102), 1,
      sym__callee,
    ACTIONS(271), 2,
      sym_istr,
      sym_str,
    STATE(72), 4,
      sym__strong_expr,
      sym_identifier_value,
      sym_call,
      sym__value,
  [1714] = 7,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(273), 1,
      sym_int,
    STATE(102), 1,
      sym__callee,
    ACTIONS(271), 2,
      sym_istr,
      sym_str,
    STATE(72), 4,
      sym__strong_expr,
      sym_identifier_value,
      sym_call,
      sym__value,
  [1740] = 7,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(277), 1,
      sym_int,
    STATE(102), 1,
      sym__callee,
    ACTIONS(275), 2,
      sym_istr,
      sym_str,
    STATE(108), 4,
      sym__strong_expr,
      sym_identifier_value,
      sym_call,
      sym__value,
  [1766] = 2,
    ACTIONS(281), 2,
      anon_sym_PIPE,
      anon_sym_GT,
    ACTIONS(279), 8,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT,
      anon_sym_GT_GT,
  [1781] = 4,
    ACTIONS(283), 1,
      anon_sym_LF,
    STATE(51), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(152), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_istr,
      sym_str,
    ACTIONS(157), 4,
      anon_sym_let,
      sym_int,
      sym_identifier,
      sym_word,
  [1800] = 4,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(286), 2,
      sym_istr,
      sym_str,
    ACTIONS(288), 3,
      sym_int,
      sym_identifier,
      sym_word,
    STATE(50), 3,
      sym__expr,
      sym__value,
      sym__word,
  [1818] = 3,
    ACTIONS(294), 1,
      anon_sym_RBRACE,
    ACTIONS(290), 4,
      anon_sym_let,
      sym_int,
      sym_identifier,
      sym_word,
    ACTIONS(292), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_istr,
      sym_str,
  [1834] = 3,
    ACTIONS(296), 1,
      anon_sym_RBRACE,
    ACTIONS(290), 4,
      anon_sym_let,
      sym_int,
      sym_identifier,
      sym_word,
    ACTIONS(292), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_istr,
      sym_str,
  [1850] = 2,
    ACTIONS(298), 2,
      sym_int,
      sym_identifier,
    ACTIONS(162), 6,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_istr,
      sym_str,
  [1863] = 2,
    ACTIONS(290), 4,
      anon_sym_let,
      sym_int,
      sym_identifier,
      sym_word,
    ACTIONS(292), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_istr,
      sym_str,
  [1876] = 2,
    ACTIONS(302), 1,
      anon_sym_LPAREN,
    ACTIONS(300), 7,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_in,
  [1889] = 1,
    ACTIONS(304), 7,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_in,
  [1899] = 1,
    ACTIONS(306), 7,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_in,
  [1909] = 1,
    ACTIONS(308), 7,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_in,
  [1919] = 2,
    ACTIONS(312), 3,
      sym_int,
      sym_identifier,
      sym_word,
    ACTIONS(310), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_istr,
      sym_str,
  [1931] = 2,
    ACTIONS(316), 3,
      sym_int,
      sym_identifier,
      sym_word,
    ACTIONS(314), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_istr,
      sym_str,
  [1943] = 2,
    ACTIONS(320), 3,
      sym_int,
      sym_identifier,
      sym_word,
    ACTIONS(318), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_istr,
      sym_str,
  [1955] = 2,
    ACTIONS(324), 1,
      anon_sym_PIPE,
    ACTIONS(322), 6,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [1967] = 2,
    ACTIONS(324), 1,
      anon_sym_PIPE,
    ACTIONS(326), 6,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [1979] = 2,
    ACTIONS(330), 3,
      sym_int,
      sym_identifier,
      sym_word,
    ACTIONS(328), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_istr,
      sym_str,
  [1991] = 2,
    ACTIONS(334), 3,
      sym_int,
      sym_identifier,
      sym_word,
    ACTIONS(332), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_istr,
      sym_str,
  [2003] = 1,
    ACTIONS(336), 7,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_in,
  [2013] = 2,
    ACTIONS(340), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
    ACTIONS(338), 4,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [2024] = 2,
    ACTIONS(342), 3,
      anon_sym_LBRACK,
      sym_istr,
      sym_str,
    ACTIONS(344), 3,
      sym_int,
      sym_identifier,
      sym_word,
  [2035] = 2,
    ACTIONS(346), 3,
      anon_sym_LBRACK,
      sym_istr,
      sym_str,
    ACTIONS(348), 3,
      sym_int,
      sym_identifier,
      sym_word,
  [2046] = 1,
    ACTIONS(350), 5,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_in,
  [2054] = 3,
    ACTIONS(354), 1,
      anon_sym_COMMA,
    ACTIONS(356), 1,
      anon_sym_in,
    ACTIONS(352), 2,
      anon_sym_LF,
      anon_sym_RBRACE,
  [2065] = 1,
    ACTIONS(124), 4,
      anon_sym_LF,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_in,
  [2072] = 1,
    ACTIONS(132), 4,
      anon_sym_LF,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_in,
  [2079] = 1,
    ACTIONS(128), 4,
      anon_sym_LF,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_in,
  [2086] = 3,
    ACTIONS(354), 1,
      anon_sym_COMMA,
    ACTIONS(360), 1,
      anon_sym_in,
    ACTIONS(358), 2,
      anon_sym_LF,
      anon_sym_RBRACE,
  [2097] = 4,
    ACTIONS(362), 1,
      anon_sym_in,
    ACTIONS(364), 1,
      sym_identifier,
    STATE(73), 1,
      sym_var_def,
    STATE(79), 1,
      aux_sym_cmd_vars_repeat1,
  [2110] = 4,
    ACTIONS(366), 1,
      anon_sym_in,
    ACTIONS(368), 1,
      sym_identifier,
    STATE(79), 1,
      aux_sym_cmd_vars_repeat1,
    STATE(110), 1,
      sym_var_def,
  [2123] = 1,
    ACTIONS(371), 4,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [2130] = 4,
    ACTIONS(364), 1,
      sym_identifier,
    ACTIONS(373), 1,
      anon_sym_in,
    STATE(77), 1,
      sym_var_def,
    STATE(78), 1,
      aux_sym_cmd_vars_repeat1,
  [2143] = 3,
    ACTIONS(375), 1,
      anon_sym_LF,
    ACTIONS(377), 1,
      anon_sym_LBRACE,
    STATE(83), 1,
      aux_sym_source_file_repeat1,
  [2153] = 3,
    ACTIONS(58), 1,
      anon_sym_LF,
    ACTIONS(379), 1,
      anon_sym_LBRACE,
    STATE(26), 1,
      aux_sym_source_file_repeat1,
  [2163] = 3,
    ACTIONS(379), 1,
      anon_sym_LBRACE,
    ACTIONS(381), 1,
      anon_sym_LF,
    STATE(85), 1,
      aux_sym_source_file_repeat1,
  [2173] = 3,
    ACTIONS(58), 1,
      anon_sym_LF,
    ACTIONS(383), 1,
      anon_sym_LBRACE,
    STATE(26), 1,
      aux_sym_source_file_repeat1,
  [2183] = 2,
    ACTIONS(387), 1,
      anon_sym_SEMI,
    ACTIONS(385), 2,
      anon_sym_LF,
      anon_sym_RBRACE,
  [2191] = 2,
    STATE(25), 1,
      sym_cmd_op,
    ACTIONS(389), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [2199] = 2,
    ACTIONS(387), 1,
      anon_sym_SEMI,
    ACTIONS(391), 2,
      anon_sym_LF,
      anon_sym_RBRACE,
  [2207] = 2,
    ACTIONS(393), 1,
      anon_sym_COMMA,
    ACTIONS(395), 1,
      anon_sym_RBRACK,
  [2214] = 2,
    ACTIONS(182), 1,
      anon_sym_RBRACK,
    ACTIONS(393), 1,
      anon_sym_COMMA,
  [2221] = 1,
    ACTIONS(397), 2,
      anon_sym_LF,
      anon_sym_RBRACE,
  [2226] = 2,
    ACTIONS(399), 1,
      anon_sym_LF,
    ACTIONS(401), 1,
      anon_sym_RBRACE,
  [2233] = 2,
    ACTIONS(393), 1,
      anon_sym_COMMA,
    ACTIONS(403), 1,
      anon_sym_RPAREN,
  [2240] = 2,
    ACTIONS(393), 1,
      anon_sym_COMMA,
    ACTIONS(405), 1,
      anon_sym_RBRACK,
  [2247] = 1,
    ACTIONS(366), 2,
      anon_sym_in,
      sym_identifier,
  [2252] = 1,
    ACTIONS(407), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [2257] = 2,
    ACTIONS(230), 1,
      anon_sym_RBRACK,
    ACTIONS(393), 1,
      anon_sym_COMMA,
  [2264] = 2,
    ACTIONS(220), 1,
      anon_sym_RPAREN,
    ACTIONS(393), 1,
      anon_sym_COMMA,
  [2271] = 1,
    ACTIONS(409), 2,
      anon_sym_LF,
      anon_sym_RBRACE,
  [2276] = 2,
    ACTIONS(294), 1,
      anon_sym_RBRACE,
    ACTIONS(411), 1,
      anon_sym_LF,
  [2283] = 2,
    ACTIONS(413), 1,
      sym_identifier,
    STATE(109), 1,
      sym_var_def,
  [2290] = 2,
    ACTIONS(415), 1,
      anon_sym_LPAREN,
    STATE(60), 1,
      sym_args,
  [2297] = 1,
    ACTIONS(417), 1,
      anon_sym_RPAREN,
  [2301] = 1,
    ACTIONS(419), 1,
      anon_sym_RBRACE,
  [2305] = 1,
    ACTIONS(387), 1,
      anon_sym_SEMI,
  [2309] = 1,
    ACTIONS(421), 1,
      anon_sym_PIPE,
  [2313] = 1,
    ACTIONS(423), 1,
      anon_sym_RBRACE,
  [2317] = 1,
    ACTIONS(425), 1,
      anon_sym_RPAREN,
  [2321] = 1,
    ACTIONS(427), 1,
      anon_sym_SEMI,
  [2325] = 1,
    ACTIONS(354), 1,
      anon_sym_COMMA,
  [2329] = 1,
    ACTIONS(429), 1,
      anon_sym_EQ,
  [2333] = 1,
    ACTIONS(431), 1,
      anon_sym_cmd,
  [2337] = 1,
    ACTIONS(433), 1,
      anon_sym_RBRACE,
  [2341] = 1,
    ACTIONS(435), 1,
      anon_sym_LF,
  [2345] = 1,
    ACTIONS(437), 1,
      sym_identifier,
  [2349] = 1,
    ACTIONS(439), 1,
      anon_sym_SEMI,
  [2353] = 1,
    ACTIONS(441), 1,
      ts_builtin_sym_end,
  [2357] = 1,
    ACTIONS(393), 1,
      anon_sym_COMMA,
  [2361] = 1,
    ACTIONS(443), 1,
      anon_sym_RBRACE,
  [2365] = 1,
    ACTIONS(445), 1,
      anon_sym_cmd,
  [2369] = 1,
    ACTIONS(447), 1,
      anon_sym_EQ,
  [2373] = 1,
    ACTIONS(449), 1,
      anon_sym_LPAREN,
  [2377] = 1,
    ACTIONS(451), 1,
      anon_sym_LPAREN,
  [2381] = 1,
    ACTIONS(453), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 68,
  [SMALL_STATE(4)] = 136,
  [SMALL_STATE(5)] = 204,
  [SMALL_STATE(6)] = 272,
  [SMALL_STATE(7)] = 340,
  [SMALL_STATE(8)] = 408,
  [SMALL_STATE(9)] = 467,
  [SMALL_STATE(10)] = 526,
  [SMALL_STATE(11)] = 585,
  [SMALL_STATE(12)] = 629,
  [SMALL_STATE(13)] = 673,
  [SMALL_STATE(14)] = 726,
  [SMALL_STATE(15)] = 779,
  [SMALL_STATE(16)] = 832,
  [SMALL_STATE(17)] = 865,
  [SMALL_STATE(18)] = 888,
  [SMALL_STATE(19)] = 911,
  [SMALL_STATE(20)] = 956,
  [SMALL_STATE(21)] = 979,
  [SMALL_STATE(22)] = 1021,
  [SMALL_STATE(23)] = 1063,
  [SMALL_STATE(24)] = 1084,
  [SMALL_STATE(25)] = 1123,
  [SMALL_STATE(26)] = 1162,
  [SMALL_STATE(27)] = 1185,
  [SMALL_STATE(28)] = 1218,
  [SMALL_STATE(29)] = 1250,
  [SMALL_STATE(30)] = 1276,
  [SMALL_STATE(31)] = 1308,
  [SMALL_STATE(32)] = 1340,
  [SMALL_STATE(33)] = 1372,
  [SMALL_STATE(34)] = 1398,
  [SMALL_STATE(35)] = 1424,
  [SMALL_STATE(36)] = 1446,
  [SMALL_STATE(37)] = 1478,
  [SMALL_STATE(38)] = 1500,
  [SMALL_STATE(39)] = 1532,
  [SMALL_STATE(40)] = 1549,
  [SMALL_STATE(41)] = 1566,
  [SMALL_STATE(42)] = 1593,
  [SMALL_STATE(43)] = 1610,
  [SMALL_STATE(44)] = 1637,
  [SMALL_STATE(45)] = 1654,
  [SMALL_STATE(46)] = 1671,
  [SMALL_STATE(47)] = 1688,
  [SMALL_STATE(48)] = 1714,
  [SMALL_STATE(49)] = 1740,
  [SMALL_STATE(50)] = 1766,
  [SMALL_STATE(51)] = 1781,
  [SMALL_STATE(52)] = 1800,
  [SMALL_STATE(53)] = 1818,
  [SMALL_STATE(54)] = 1834,
  [SMALL_STATE(55)] = 1850,
  [SMALL_STATE(56)] = 1863,
  [SMALL_STATE(57)] = 1876,
  [SMALL_STATE(58)] = 1889,
  [SMALL_STATE(59)] = 1899,
  [SMALL_STATE(60)] = 1909,
  [SMALL_STATE(61)] = 1919,
  [SMALL_STATE(62)] = 1931,
  [SMALL_STATE(63)] = 1943,
  [SMALL_STATE(64)] = 1955,
  [SMALL_STATE(65)] = 1967,
  [SMALL_STATE(66)] = 1979,
  [SMALL_STATE(67)] = 1991,
  [SMALL_STATE(68)] = 2003,
  [SMALL_STATE(69)] = 2013,
  [SMALL_STATE(70)] = 2024,
  [SMALL_STATE(71)] = 2035,
  [SMALL_STATE(72)] = 2046,
  [SMALL_STATE(73)] = 2054,
  [SMALL_STATE(74)] = 2065,
  [SMALL_STATE(75)] = 2072,
  [SMALL_STATE(76)] = 2079,
  [SMALL_STATE(77)] = 2086,
  [SMALL_STATE(78)] = 2097,
  [SMALL_STATE(79)] = 2110,
  [SMALL_STATE(80)] = 2123,
  [SMALL_STATE(81)] = 2130,
  [SMALL_STATE(82)] = 2143,
  [SMALL_STATE(83)] = 2153,
  [SMALL_STATE(84)] = 2163,
  [SMALL_STATE(85)] = 2173,
  [SMALL_STATE(86)] = 2183,
  [SMALL_STATE(87)] = 2191,
  [SMALL_STATE(88)] = 2199,
  [SMALL_STATE(89)] = 2207,
  [SMALL_STATE(90)] = 2214,
  [SMALL_STATE(91)] = 2221,
  [SMALL_STATE(92)] = 2226,
  [SMALL_STATE(93)] = 2233,
  [SMALL_STATE(94)] = 2240,
  [SMALL_STATE(95)] = 2247,
  [SMALL_STATE(96)] = 2252,
  [SMALL_STATE(97)] = 2257,
  [SMALL_STATE(98)] = 2264,
  [SMALL_STATE(99)] = 2271,
  [SMALL_STATE(100)] = 2276,
  [SMALL_STATE(101)] = 2283,
  [SMALL_STATE(102)] = 2290,
  [SMALL_STATE(103)] = 2297,
  [SMALL_STATE(104)] = 2301,
  [SMALL_STATE(105)] = 2305,
  [SMALL_STATE(106)] = 2309,
  [SMALL_STATE(107)] = 2313,
  [SMALL_STATE(108)] = 2317,
  [SMALL_STATE(109)] = 2321,
  [SMALL_STATE(110)] = 2325,
  [SMALL_STATE(111)] = 2329,
  [SMALL_STATE(112)] = 2333,
  [SMALL_STATE(113)] = 2337,
  [SMALL_STATE(114)] = 2341,
  [SMALL_STATE(115)] = 2345,
  [SMALL_STATE(116)] = 2349,
  [SMALL_STATE(117)] = 2353,
  [SMALL_STATE(118)] = 2357,
  [SMALL_STATE(119)] = 2361,
  [SMALL_STATE(120)] = 2365,
  [SMALL_STATE(121)] = 2369,
  [SMALL_STATE(122)] = 2373,
  [SMALL_STATE(123)] = 2377,
  [SMALL_STATE(124)] = 2381,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(123),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__cmd_in_blk_repeat1, 2), SHIFT_REPEAT(81),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__cmd_in_blk_repeat1, 2), SHIFT_REPEAT(24),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__cmd_in_blk_repeat1, 2), SHIFT_REPEAT(31),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__cmd_in_blk_repeat1, 2), SHIFT_REPEAT(23),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__cmd_in_blk_repeat1, 2), SHIFT_REPEAT(23),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cmd, 1),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cmd, 1),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cmd, 2),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cmd, 2),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2), SHIFT_REPEAT(35),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2), SHIFT_REPEAT(101),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2), SHIFT_REPEAT(49),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2), SHIFT_REPEAT(31),
  [94] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2), SHIFT_REPEAT(123),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2), SHIFT_REPEAT(82),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2), SHIFT_REPEAT(116),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2), SHIFT_REPEAT(116),
  [106] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2), SHIFT_REPEAT(57),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_cmd_repeat1, 2),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_cmd_repeat1, 2), SHIFT_REPEAT(31),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_cmd_repeat1, 2),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_cmd_repeat1, 2), SHIFT_REPEAT(16),
  [121] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_cmd_repeat1, 2), SHIFT_REPEAT(16),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 4),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__value, 4),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 2),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__value, 2),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 3),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__value, 3),
  [136] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__cmd_list_repeat1, 2), SHIFT_REPEAT(24),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__cmd_list_repeat1, 2), SHIFT_REPEAT(31),
  [142] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__cmd_list_repeat1, 2), SHIFT_REPEAT(23),
  [145] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__cmd_list_repeat1, 2), SHIFT_REPEAT(23),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cmd_name, 1),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cmd_name, 1),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [154] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(26),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_args_repeat1, 2), SHIFT_REPEAT(49),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_args_repeat1, 2),
  [164] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_args_repeat1, 2), SHIFT_REPEAT(31),
  [167] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_args_repeat1, 2), SHIFT_REPEAT(118),
  [170] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_args_repeat1, 2), SHIFT_REPEAT(118),
  [173] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_args_repeat1, 2), SHIFT_REPEAT(57),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_cmd_repeat2, 2),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_cmd_repeat2, 2),
  [204] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_cmd_repeat2, 2), SHIFT_REPEAT(71),
  [207] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_cmd_repeat2, 2), SHIFT_REPEAT(71),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cmd, 3),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cmd, 3),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_line, 1),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement_line, 1),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [224] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_line, 2),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement_line, 2),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [234] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__cmd_blk, 7),
  [238] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__cmd_blk, 7),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 2),
  [242] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 2),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__cmd_blk, 4),
  [246] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__cmd_blk, 4),
  [248] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pipeline_repeat1, 2), SHIFT_REPEAT(31),
  [251] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pipeline_repeat1, 2), SHIFT_REPEAT(23),
  [254] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pipeline_repeat1, 2), SHIFT_REPEAT(23),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__cmd_blk, 5),
  [259] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__cmd_blk, 5),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 3),
  [263] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_statement, 3),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__cmd_blk, 6),
  [267] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__cmd_blk, 6),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [273] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [277] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_redir, 2),
  [281] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_redir, 2),
  [283] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(51),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [288] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [290] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__cmd_in_blk_repeat1, 2),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__cmd_in_blk_repeat1, 2),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__cmd_in_blk, 2),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__cmd_in_blk, 3),
  [298] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_args_repeat1, 2),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier_value, 1),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__callee, 1),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_args, 4),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_args, 2),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cmd_vars, 3),
  [312] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cmd_vars, 3),
  [314] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cmd_vars, 4),
  [316] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cmd_vars, 4),
  [318] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cmd_vars, 2),
  [320] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cmd_vars, 2),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipeline, 2),
  [324] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [326] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipeline, 1),
  [328] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__cmd_list_repeat1, 2),
  [330] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__cmd_list_repeat1, 2),
  [332] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cmd_op, 1),
  [334] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cmd_op, 1),
  [336] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_args, 3),
  [338] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cmd_chain, 1),
  [340] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__cmd_chain_part, 1),
  [342] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pipeline_repeat1, 2),
  [344] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pipeline_repeat1, 2),
  [346] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_redir_kind, 1),
  [348] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_redir_kind, 1),
  [350] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_def, 3),
  [352] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cmd_var_stmt, 3),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [358] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cmd_var_stmt, 2),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [362] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [364] = {.entry = {.count = 1, .reusable = false}}, SHIFT(121),
  [366] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_cmd_vars_repeat1, 2),
  [368] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_cmd_vars_repeat1, 2), SHIFT_REPEAT(111),
  [371] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cmd_chain, 3),
  [373] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [385] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__cmd_list, 2),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [389] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [391] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__cmd_list, 1),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [397] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cmd_ctx, 1),
  [399] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [401] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__cmd_in_blk, 1),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [407] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__cmd_chain_part, 3),
  [409] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cmd_ctx, 2),
  [411] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [413] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [415] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [417] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [419] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [421] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [423] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [425] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [427] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [429] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [431] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [433] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [435] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [437] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [439] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [441] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [443] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [445] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_capture, 4),
  [447] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [449] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__callee, 3),
  [451] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [453] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_rsh(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
